#!/usr/bin/env python3
"""Generate supabase/seed_import.sql (v2) from the approved JSON.

Same data as v1, generated the same way (nothing retyped). Differences:
  * runs in ONE transaction (all-or-nothing)
  * program_tasks / program_checklist_items: ON CONFLICT DO NOTHING
    -> re-running the seed only adds missing rows and NEVER overwrites
       what the admin edited in the panel (titles, descriptions, video
       URLs, resources, checklist text)
  * ends with a self-check (132 days / 396 tasks / 335 items)
Usage: python3 scripts/generate_seed.py
"""
import json, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((root / 'supabase/level-up-132-days-schema.json').read_text(encoding='utf-8'))

def q(v):
    if v is None: return 'null'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, (int, float)): return str(v)
    return "'" + str(v).replace("'", "''") + "'"

days = sorted(data['days'].values(), key=lambda d: d['day'])
out = []
w = out.append
w('-- LEVEL UP WITH ALAA — BAC 2027')
w('-- seed_import.sql v2 — generated by scripts/generate_seed.py from level-up-132-days-schema.json')
w('-- Same values as v1. Safe to re-run: never duplicates rows and never overwrites')
w('-- content edited from the admin panel (titles, descriptions, videos, resources, checklist text).')
w('-- Run AFTER supabase/schema.sql.\n')
w('begin;\n')

w('-- program_days')
w('insert into public.program_days (day_number, month) values')
w(',\n'.join(f"({d['day']}, {d['month']})" for d in days))
w('on conflict (day_number) do update set month = excluded.month;\n')

w('-- program_tasks (insert-only: admin edits are preserved)')
w('insert into public.program_tasks (id, day_number, task_number, subject, subject_label_ar, task_type, title, description, has_video, video_url, thumbnail_url, resources) values')
rows = []
for d in days:
    for t in d['tasks']:
        rows.append('(' + ', '.join([
            q(f"{d['day']}-{t['task_number']}"), q(d['day']), q(t['task_number']), q(t['subject']),
            q(t['subject_label_ar']), q(t['task_type']), q(t['title']), q(t['description']),
            q(bool(t['has_video'])), q(t['video_url']), 'null',
            q(json.dumps(t['resources'], ensure_ascii=False)) + '::jsonb']) + ')')
w(',\n'.join(rows))
w('on conflict (id) do nothing;\n')

w('-- program_checklist_items (insert-only: admin edits are preserved)')
w('insert into public.program_checklist_items (id, task_id, item_index, text) values')
rows = []
for d in days:
    for t in d['tasks']:
        tid = f"{d['day']}-{t['task_number']}"
        for i, text in enumerate(t['checklist_items']):
            rows.append(f"({q(f'{tid}::{i}')}, {q(tid)}, {i}, {q(text)})")
w(',\n'.join(rows))
w('on conflict (id) do nothing;\n')

w('-- weekly_reviews')
w('insert into public.weekly_reviews (week_number, from_day, to_day, max_stars) values')
w(',\n'.join(f"({r['week_number']}, {r['from_day']}, {r['to_day']}, {q(r['max_stars'])})" for r in data['weekly_reviews']))
w('on conflict (week_number) do update set from_day=excluded.from_day, to_day=excluded.to_day, max_stars=excluded.max_stars;\n')

w('-- monthly_reviews')
w('insert into public.monthly_reviews (month_number, from_day, to_day, max_stars) values')
w(',\n'.join(f"({r['month_number']}, {r['from_day']}, {r['to_day']}, {q(r['max_stars'])})" for r in data['monthly_reviews']))
w('on conflict (month_number) do update set from_day=excluded.from_day, to_day=excluded.to_day, max_stars=excluded.max_stars;\n')

w('-- final_check_metrics')
w('insert into public.final_check_metrics (label, value, target) values')
w(',\n'.join(f"({q(m['label'])}, {m['value']}, {m['target']})" for m in data['final_check']['metrics']))
w('on conflict (label) do update set value=excluded.value, target=excluded.target;\n')

n_days = len(days); n_tasks = sum(len(d['tasks']) for d in days)
n_items = sum(len(t['checklist_items']) for d in days for t in d['tasks'])
w('-- self-check: abort (and roll back) if anything is missing')
w('do $$ begin')
w(f"  if (select count(*) from public.program_days) <> {n_days} then raise exception 'seed check failed: program_days'; end if;")
w(f"  if (select count(*) from public.program_tasks) <> {n_tasks} then raise exception 'seed check failed: program_tasks'; end if;")
w(f"  if (select count(*) from public.program_checklist_items) <> {n_items} then raise exception 'seed check failed: program_checklist_items'; end if;")
w(f"  if (select count(*) from public.weekly_reviews) <> {len(data['weekly_reviews'])} then raise exception 'seed check failed: weekly_reviews'; end if;")
w(f"  if (select count(*) from public.monthly_reviews) <> {len(data['monthly_reviews'])} then raise exception 'seed check failed: monthly_reviews'; end if;")
w(f"  raise notice 'seed OK: {n_days} days, {n_tasks} tasks, {n_items} checklist items';")
w('end $$;\n')
w('commit;')

(root / 'supabase/seed_import.sql').write_text('\n'.join(out) + '\n', encoding='utf-8')
print(f'written: {n_days} days, {n_tasks} tasks, {n_items} items')
